[tool.poetry]
name = "dz-19-1"
version = "0.1.0"
description = ""
authors = ["Stepanryazan <offish.sk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
